baseurl: /
permalink: /restaurante/:title
#markdown: rdiscount
prose:
  rooturl: '_posts'
  siteurl: 'http://consorciobertiz.github.io'
  media: 'media'
  metadata:
    _posts/restaurantes:
      - name: "category"
        field:
          element: "hidden"
          value: "restaurante"
      - name: "layout"
        field:
          element: "hidden"
          value: "restaurante"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "telefono"
        field:
          element: "text"
          label: "Teléfono"
          value: ""
      - name: "idioma"
        field:
          element: "select"
          label: "Selecciona idioma"
          placeholder: "Castellano"
          options:
            - name: "Castellano"
              value: "es"
            - name: "Euskara"
              value: "eu"
            - name: "Ingles"
              value: "en"
            - name: "Frances"
              value: "fr"
          selected: "es"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Abre los"
          placeholder: "Selecciona días"
          options:
            - name: "Lunes - Mediodía"
              value: "lunes-mediodia"
            - name: "Lunes - Noche"
              value: "lunes-noche"
            - name: "Martes - Mediodía"
              value: "martes-mediodia"
            - name: "Martes - Noche"
              value: "martes-noche"
            - name: "Miércoles - Mediodía"
              value: "miercoles-mediodia"
            - name: "Miércoles - Noche"
              value: "miercoles-noche"
            - name: "Jueves - Mediodía"
              value: "jueves-mediodia"
            - name: "Jueves - Noche"
              value: "jueves-noche"
            - name: "Viernes - Mediodía"
              value: "viernes-mediodia"
            - name: "Viernes - Noche"
              value: "viernes-noche"
            - name: "Sabado - Mediodía"
              value: "sabado-mediodia"
            - name: "Sabado - Noche"
              value: "sabado-noche"
            - name: "Domingo - Mediodía"
              value: "domingo-mediodia"
            - name: "Domingo - Noche"
              value: "domingo-noche"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "category"
        field:
          element: "hidden"
          value: "home_es"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "periodo"
        field:
          element: "text"
          label: "Periodo de apertura"
          value: ""
      - name: "idioma"
        field:
          element: "hidden"
          value: "es"
t:
  es:
    Lunes: "Lunes"
    Martes: "Martes"
    Miercoles: "Miércoles"
    Jueves: "Jueves"
    Viernes: "Viernes"
    Sabado: "Sabado"
    Domingo: "Domingo"
    Mediodia: "Mediodía"
    Noche: "Noche"
    Site_Title: "Restaurantes de guardia en Baztan-Bidasoa"
    Site_Description: "Calendario de apertura de los restaurantes de guardia en Baztan-Bidasoa"
    Home_Lead: "Este es el calendario de apertura de los restaurantes del área Baztan Bidasoa. <br/> Algunos restaurantes de la zona no están abiertos todos los días para comer y cenar. Antes de desplazarse a uno de ellos, revise cuáles están abiertos en el momento en el que usted lo necesita."
    MasRestaurantes: "Más restaurantes en Baztan-Bidasoa"
  en:
    Lunes: "Monday"
    Martes: "Tuesday"
    Miercoles: "Wednesday"
    Jueves: "Thursday"
    Viernes: "Friday"
    Sabado: "Saturday"
    Domingo: "Sunday"
    Mediodia: "Lunchtime"
    Noche: "Evening meal"
    Site_Title: "Restaurant open in Baztan-Bidasoa"
    Site_Description: "Calendar of open restaurants in Baztan-Bidasoa"
    Home_Lead: "This is the calendar with open restaurants in de Baztan-Bidasoa area. Some restaurants of this area aren't open all days for lunch and evening meal. Before to go to one of them, check which are open at the moment you need it."
    MasRestaurantes: "More restaurants in Baztan-Bidasoa"
  fr:
    Lunes: "Lundi"
    Martes: "Mardi"
    Miercoles: "Mercredi"
    Jueves: "Jeudi"
    Viernes: "Vendredi"
    Sabado: "Samedi"
    Domingo: "Dimanche"
    Mediodia: "Midi"
    Noche: "Soir"
    Site_Title: "Restaurants ouverts au Baztan-Bidasoa"
    Site_Description: "Calendrier des restaurants ouverts au Baztan-Bidasoa."
    Home_Lead: "Ceci est un calendrier avec les restaurants ouverts dans la région du Baztan-Bidasoa. Avant de vous déplacer, veuillez vérifier lesquels sont ouverts au moment ou vous en avez besoin."
    MasRestaurantes: "Plus de restaurants au Baztan-Bidasoa"
  eu:
    Lunes: "Astelehena"
    Martes: "Asteartea"
    Miercoles: "Asteazkena"
    Jueves: "Osteguna"
    Viernes: "Ostirala"
    Sabado: "Larunbata"
    Domingo: "Igandea"
    Mediodia: "Eguerdian"
    Noche: "Arratsean"
    Site_Title: "Baztan-Bidasoko 'guardiazko' jatetxeak."
    Site_Description: "Baztan-Bidasoako jatetxe irekien egutegia"
    Home_Lead: "Hau da Baztan-Bidasoko zonaldearen jatetxe irekien egutegia.<br/>Jatetxe batzuk ez daude irekiak egunero bazkaldi eta afaltzeko. Joan baino lehenago, begira ezazu zeintzu dauden irekiak zuk behar duzun momentuan."
    MasRestaurantes: "Jatetxe gehiago Baztan-Bidasoa"
