baseurl: /
permalink: /restaurante/:title
#markdown: rdiscount
prose:
  rooturl: '_posts'
  siteurl: 'http://consorciobertiz.github.io'
  media: 'media'
  metadata:
    _posts/restaurantes:
      - name: "category"
        field:
          element: "hidden"
          value: "restaurante"
      - name: "layout"
        field:
          element: "hidden"
          value: "restaurante"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "telefono"
        field:
          element: "text"
          label: "Teléfono"
          value: ""
      - name: "idioma"
        field:
          element: "select"
          label: "Selecciona idioma"
          placeholder: "Castellano"
          options:
            - name: "Castellano"
              value: "es"
            - name: "Euskara"
              value: "eu"
            - name: "Ingles"
              value: "en"
            - name: "Frances"
              value: "fr"
          selected: "es"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Abre los"
          placeholder: "Selecciona días"
          options:
            - name: "Lunes - Mediodía"
              value: "lunes-mediodia"
            - name: "Lunes - Noche"
              value: "lunes-noche"
            - name: "Martes - Mediodía"
              value: "martes-mediodia"
            - name: "Martes - Noche"
              value: "martes-noche"
            - name: "Miércoles - Mediodía"
              value: "miercoles-mediodia"
            - name: "Miércoles - Noche"
              value: "miercoles-noche"
            - name: "Jueves - Mediodía"
              value: "jueves-mediodia"
            - name: "Jueves - Noche"
              value: "jueves-noche"
            - name: "Viernes - Mediodía"
              value: "viernes-mediodia"
            - name: "Viernes - Noche"
              value: "viernes-noche"
            - name: "Sabado - Mediodía"
              value: "sabado-mediodia"
            - name: "Sabado - Noche"
              value: "sabado-noche"
            - name: "Domingo - Mediodía"
              value: "domingo-mediodia"
            - name: "Domingo - Noche"
              value: "domingo-noche"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "category"
        field:
          element: "hidden"
          value: "home_es"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "periodo"
        field:
          element: "text"
          label: "Periodo de apertura"
          value: ""
      - name: "idioma"
        field:
          element: "hidden"
          value: "es"
t:
  es:
    Lunes: "Lunes"
    Martes: "Martes"
    Miercoles: "Miércoles"
    Jueves: "Jueves"
    Viernes: "Viernes"
    Sabado: "Sabado"
    Domingo: "Domingo"
    Mediodia: "Mediodía"
    Noche: "Noche"
    Site_Title: "Restaurantes de Baztán-Bidasoa"
    Site_Description: "Calendario de apertura de los restaurantes de Baztan-Bidasoa"
    Home_Title1: "Restaurantes de Baztán-Bidasoa"
    Home_Title: "<span>Restaurantes de </span>Baztán-Bidasoa"
    Home_Lead: "Este es el calendario de apertura de los restaurantes del área Baztán Bidasoa. <br/> Algunos restaurantes de la zona no están abiertos todos los días para comer y cenar. Antes de desplazarse a uno de ellos, revise cuáles están abiertos en el momento en el que usted lo necesita."
  en:
    Lunes: "en-Lunes"
    Martes: "en-Martes"
    Miercoles: "en-Miércoles"
    Jueves: "en-Jueves"
    Viernes: "en-Viernes"
    Sabado: "en-Sabado"
    Domingo: "en-Domingo"
    Mediodia: "en-Mediodía"
    Noche: "en-Noche"
    Site_Title: "en-Restaurantes de Baztán-Bidasoa"
    Site_Description: "en-Calendario de apertura de los restaurantes de Baztan-Bidasoa"
    Home_Title1: "Restaurantes de Baztán-Bidasoa"
    Home_Title: "en-<span>Restaurantes de </span>Baztán-Bidasoa"
    Home_Lead: "en-Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
  fr:
    Lunes: "Lunes"
    Martes: "Martes"
    Miercoles: "Miércoles"
    Jueves: "Jueves"
    Viernes: "Viernes"
    Sabado: "Sabado"
    Domingo: "Domingo"
    Mediodia: "Mediodía"
    Noche: "Noche"
    Site_Title: "Restaurantes de Baztán-Bidasoa"
    Site_Description: "Calendario de apertura de los restaurantes de Baztan-Bidasoa"
    Home_Title1: "Restaurantes de Baztán-Bidasoa"
    Home_Title: "<span>Restaurantes de </span>Baztán-Bidasoa"
    Home_Lead: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
  eu:
    Lunes: "Lunes"
    Martes: "Martes"
    Miercoles: "Miércoles"
    Jueves: "Jueves"
    Viernes: "Viernes"
    Sabado: "Sabado"
    Domingo: "Domingo"
    Mediodia: "Mediodía"
    Noche: "Noche"
    Site_Title: "Restaurantes de Baztán-Bidasoa"
    Site_Description: "Calendario de apertura de los restaurantes de Baztan-Bidasoa"
    Home_Title1: "Restaurantes de Baztán-Bidasoa"
    Home_Title: "<span>Restaurantes de </span>Baztán-Bidasoa"
    Home_Lead: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
